### ISSUE TITLE
cert-manager need explanation

### ISSUE THREAD

**Issue by jvice** [newrelic/k8s-agents-operator#76]
cert-manager is not a component currently deployed to our clusters. prior to adding this, I'd like to understand the role it plays in this operator. Is it absolutely necessary?

**Comment by jordanjennings** [comment]
Having a dependency on cert-manager is a liability - it makes it more difficult for users to install, and as far as I can tell doesn't offer any value to users. It would be far more ideal for this project to internally manage the necessary self-signed cert to eliminate this dependency and streamline the installation process.

**Comment by dbudziwojskiNR** [comment]
Hi folks! Thanks for the feedback! Just wanted to let you know that we're working on alternatives solutions for TLS that don't require cert-manager. Stay tuned :)

**Comment by dbudziwojskiNR** [comment]
Hi! We're happy to say that version 0.13.0 no longer requires cert-manager. However, it is supported if desired. Cheers!
