### ISSUE TITLE
Helm Chart missing Namespace on Resources

### ISSUE THREAD

**Issue by pragmaticivan** [newrelic/k8s-agents-operator#88]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description
This helm chart is not taking into consideration which namespace is set on helm template or helm install. On the `--namespace` flag.

## Steps to Reproduce
Just use `helm template` with `--namespace`.

## Expected Behavior
If I install the operator in `newrelic` the deployment should be created in `newrelic`

## Additional context

This can be simply fixed with `namespace: {{ .Release.Namespace }}` in the helm template.

ex: https://github.com/aws/karpenter-provider-aws/blob/main/charts/karpenter/templates/deployment.yaml#L5

**Comment by dbudziwojskiNR** [comment]
Thank you for your feedback and PR! We're looking into the issue and will be in touch. Thanks!

**Comment by pragmaticivan** [comment]
Hi [dbudziwojskiNR](https://github.com/dbudziwojskiNR) any news on this one?

**Comment by dbudziwojskiNR** [comment]
Hi @pragmaticivan, we have fix in the works and expect it to be part of the next release (next week).

**Comment by pragmaticivan** [comment]
@dbudziwojskiNR so PRs are not welcome? https://github.com/newrelic/k8s-agents-operator/pull/89

**Comment by dbudziwojskiNR** [comment]
@pragmaticivan PRs are always welcome and greatly appreciated. For this particular bug, we were already working on a remediation and the fix will ship with v0.13.0. This said, if the latest version does not resolve this issue please let us know by creating another issue or feel free to open up another PR. Thank you again for your contribution!

**Comment by pragmaticivan** [comment]
ok... although the PR was opened 1 week before you even made the commit to fix the issue on your PR.
