### ISSUE TITLE
Helm chart priorityClassName is not available

### ISSUE THREAD

**Issue by dpetushkov-github** [newrelic/k8s-agents-operator#99]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description
For the most of the nri-bundle charts priorityClassName is available option and can be set via global values which is not true for k8s-agent-operator

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT give us access or passwords to your New Relic account or API keys! )

## Steps to Reproduce

[NOTE]: # ( Please be as specific as possible. )

## Expected Behavior

[NOTE]: # ( Tell us what you expected to happen. )
priorityClassName is can be set via global vars or via k8s-agent-operator values

## Relevant Logs / Console output

[NOTE]: # ( Please provide specifics of the local error logs, Browser Dev Tools console, etc. if appropriate and possible. )

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )

* ex: Browser name and version:
* ex: Operating System and version:

## Additional context

[TIP]:  # ( Add any other context about the problem here. )

**Comment by dbudziwojskiNR** [comment]
Hi! Thank you for bring this to our attention, we'll be looking into this.
